name: terraform apply

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: terraform

jobs:
  apply:
    runs-on: ubuntu-latest
    container: dockerdiggerorg/dgctl
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run terraform apply
        run: | 
          terraform init
          terraform apply -auto-approve
