name: terraform apply

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    container: dockerdiggerorg/dgctl
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run terraform apply
        run: | 
          terraform init
          terraform apply
